CREATE TABLE `web_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `last_user_id` int(11) DEFAULT NULL,
  `last_user_name` varchar(64) DEFAULT NULL,
  `created_at` int(11) NOT NULL,
  `updated_at` int(11) NOT NULL,
  `focus_count` int(11) NOT NULL DEFAULT '0',
  `favorite_count` int(11) NOT NULL DEFAULT '0',
  `view_count` int(11) NOT NULL DEFAULT '0',
  `comment_count` int(11) NOT NULL DEFAULT '0',
  `agree_count` int(11) NOT NULL DEFAULT '0',
  `against_count` int(11) NOT NULL DEFAULT '0',
  `recommend` int(1) DEFAULT '0',
  `headline` int(1) DEFAULT '0',
  `sticky` int(1) DEFAULT '0',
  `flag` tinyint(4) DEFAULT '0',
  `allow_comment` tinyint(1) NOT NULL DEFAULT '1',
  `password` varchar(64) DEFAULT NULL,
  `view` varchar(64) DEFAULT NULL,
  `layout` varchar(64) DEFAULT NULL,
  `sort_num` int(11) NOT NULL DEFAULT '0',
  `visibility` tinyint(4) NOT NULL DEFAULT '1',
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `content_type` varchar(64) NOT NULL,
  `seo_title` varchar(256) DEFAULT NULL,
  `seo_keywords` varchar(256) DEFAULT NULL,
  `seo_description` varchar(256) DEFAULT NULL,
  `title` varchar(256) NOT NULL,
  `sub_title` varchar(256) DEFAULT NULL,
  `url_alias` varchar(256) DEFAULT NULL,
  `redirect_url` varchar(256) DEFAULT NULL,
  `summary` varchar(512) DEFAULT NULL,
  `thumb` varchar(256) DEFAULT NULL,
  `thumbs` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

CREATE TABLE `cms_article_base` (
  `article_id` int(5) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `article_title` varchar(50) NOT NULL DEFAULT '' COMMENT '标题',
  `article_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文章别名slug',
  `article_excerpt` varchar(255) NOT NULL DEFAULT '' COMMENT '文章摘要',
  `article_content` mediumtext NOT NULL COMMENT '文章内容(HTML)',
  `article_url` varchar(100) NOT NULL DEFAULT '' COMMENT '调用网址:默认为本页面构造的网址',
  `category_id` smallint(4) unsigned NOT NULL COMMENT '所属分类',
  `article_template` varchar(50) NOT NULL DEFAULT '' COMMENT '模板',
  `article_seo_title` varchar(200) NOT NULL DEFAULT '' COMMENT 'SEO标题',
  `article_seo_keywords` varchar(200) NOT NULL DEFAULT '' COMMENT 'SEO关键字',
  `article_seo_description` varchar(200) NOT NULL DEFAULT '' COMMENT 'SEO描述',
  `article_reply_flag` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否启用问答留言(BOOL):0-否;1-是',
  `article_lang` varchar(5) NOT NULL DEFAULT 'cn' COMMENT '语言',
  `article_type` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '文章类型(ENUM):1-文章;2-公告',
  `article_sort` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `article_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态(BOOL):0-关闭;1-启用',
  `article_add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加世间',
  `article_image` varchar(255) NOT NULL DEFAULT '' COMMENT '文章图片',
  `user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '文章作者',
  `article_tags` varchar(255) NOT NULL DEFAULT '' COMMENT '文章标签(DOT):文章标签',
  `article_is_popular` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否热门',
  PRIMARY KEY (`article_id`) USING BTREE,
  KEY `category_id` (`category_id`,`article_sort`) USING BTREE,
  KEY `article_title` (`article_title`) USING BTREE,
  KEY `category_id_3` (`category_id`,`article_status`,`article_sort`) USING BTREE,
  KEY `category_id_2` (`category_id`,`article_type`,`article_status`,`article_sort`) USING BTREE,
  KEY `article_sort` (`user_id`,`category_id`,`article_status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1037 DEFAULT CHARSET=utf8 COMMENT='文章内容';